keys:
  - &personal age1dmx28jc6tturgjzd3s2a5sn9689h69nq04tyrvle4um8wv5jvaqquc9hpu
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini|sops)$
    key_groups:
      - age:
          - *personal